name: Test Build & Lint
on:
  push:
    paths:
    - 'src/**'
    - '*.json'
    - '*.js'
    - '*.yaml'
  pull_request:
    paths:
    - 'src/**'
    - '*.json'
    - '*.js'
    - '*.yaml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Cache pnpm modules
      uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-

    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.16.0
        run_install: |
          - args: [--frozen-lockfile]

    - name: Lint
      run: pnpm run lint

  build:
    name: Test Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Cache pnpm modules
      uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-

    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.16.0
        run_install: |
          - args: [--frozen-lockfile]

    - name: Test Build
      run: pnpm run build:test
